### ISSUE TITLE
NC program can only contain one tool.

### ISSUE THREAD

**Issue by sgaechter** [Klaus-Michael/estlcam_posts_processor#1]
I recently wantet to use the estlcam-post-processor you provided. Unfortunately I always get the Error "NC program can only contain one tool." if I try to export a cam with more then one tool used in the same setup. 
I own  Fusion360 Pro License. When I use the grbl-post-processor, I don't have troubles. I didn't found any information if this is a limitation of estlcam. Do you know how to solve this issue?
[1001.log](https://github.com/Klaus-Michael/estlcam_posts_processor/files/5952675/1001.log)

**Comment by Klaus-Michael** [comment]
Hello Sven,

are you sure that you are indeed using the post from THIS github project?
your logfile points to 
C:\Users\sven.gachter\AppData\Roaming\Autodesk\CAM360\cache\posts\estlcam.cps
on my system this is the path to the estlcam post from Autodesk which does not support multiple tools.
The Vendor and Legal information 
`Vendor url: https://www.estlcam.de/
Legal: Copyright (C) 2012-2020 by Autodesk, Inc.`

points to the autodesk post as well as well as the error message from line 214.

Please check if you use indeed the post that you want to use.

Best Regards,
Klaus

**Comment by sgaechter** [comment]
Hello Klaus.
Thanks for your quick response. Indeed, I used the builtin post-processor of Fusion360. 
I could fix it by replacing the builtin estlcam.cpp with the one you provide. Now everything works like a charm. My crafting evening is saved!
Regards
Sven
